<?php
$pageTitle='Remodeling Articles & Planning Guides';
$pageDescription='Practical remodeling guidance for Western New York basements, kitchens, bathrooms, and full-room projects.';
require __DIR__.'/includes/header.php';
$posts=require __DIR__.'/data/blogdata.php';
$featuredKey=array_key_first($posts); $featured=$posts[$featuredKey];
?>
<section class="page-banner article-banner"><div class="container"><span class="eyebrow">C2C PLANNING LIBRARY</span><h1>Clear answers before construction begins.</h1><p>Practical guidance for planning scope, selections, milestones, and closeout across Western New York remodeling projects.</p></div></section>
<section class="section"><div class="container"><a class="featured-article reveal" href="<?=e(url('post.php?slug='.$featuredKey))?>"><div class="featured-article-image"><img src="<?=e($featured['image'])?>" alt="<?=e($featured['title'])?>"></div><div class="featured-article-copy"><span class="article-meta"><?=e($featured['category'])?> · <?=e($featured['read'])?></span><h2><?=e($featured['title'])?></h2><p><?=e($featured['excerpt'])?></p><span class="text-link">Read the complete guide <?=icon('arrow')?></span></div></a></div></section>
<section class="section bg-mist"><div class="container"><div class="section-head-row reveal"><div><span class="eyebrow dark">LATEST INSIGHTS</span><h2>Plan with fewer unknowns.</h2></div><p>Each article gives homeowners a direct answer, the process behind it, common mistakes, and realistic scope considerations.</p></div><div class="article-grid"><?php $i=0; foreach($posts as $slug=>$post): if($i++===0) continue; ?><article class="article-card reveal"><a class="article-card-image" href="<?=e(url('post.php?slug='.$slug))?>"><img loading="lazy" src="<?=e($post['image'])?>" alt="<?=e($post['title'])?>"><span><?=e($post['category'])?></span></a><div><small><?=e($post['date'])?> · <?=e($post['read'])?></small><h3><a href="<?=e(url('post.php?slug='.$slug))?>"><?=e($post['title'])?></a></h3><p><?=e($post['excerpt'])?></p><a class="text-link" href="<?=e(url('post.php?slug='.$slug))?>">Read article <?=icon('arrow')?></a></div></article><?php endforeach; ?></div></div></section>
<section class="section"><div class="container planning-cta reveal"><div><span class="icon-box large"><?=icon('calendar')?></span><span class="eyebrow dark">YOUR PROJECT, YOUR QUESTIONS</span><h2>Ready to turn planning into a documented scope?</h2><p>Book a focused consultation and we will discuss your room, priorities, timing, and the best next step.</p></div><a class="btn btn-primary" href="<?=e(url('contact.php?intent=consult'))?>">Book a Consult</a></div></section>
<?php require __DIR__.'/includes/footer.php'; ?>
