<?php
$posts=require __DIR__.'/data/blogdata.php';
$slug=preg_replace('/[^a-z0-9-]/','',$_GET['slug']??'');
if(!$slug || !isset($posts[$slug])){http_response_code(404);$pageTitle='Article not found';require __DIR__.'/includes/header.php';echo '<section class="section"><div class="container narrow centered"><h1>Article not found</h1><p>The guide you requested is not available.</p><a class="btn btn-primary" href="'.e(url('articles.php')).'">View all articles</a></div></section>';require __DIR__.'/includes/footer.php';exit;}
$post=$posts[$slug];$pageTitle=$post['title'];$pageDescription=$post['excerpt'];require __DIR__.'/includes/header.php';
$recent=array_filter($posts,fn($p,$k)=>$k!==$slug,ARRAY_FILTER_USE_BOTH);$recent=array_slice($recent,0,4,true);
?>
<section class="post-hero"><div class="container narrow centered"><span class="eyebrow"><?=e(strtoupper($post['category']))?></span><h1><?=e($post['title'])?></h1><div class="post-byline"><span><?=icon('calendar')?> <?=e($post['date'])?></span><span><?=icon('clock')?> <?=e($post['read'])?></span></div></div></section>
<div class="container post-featured reveal"><img src="<?=e($post['image'])?>" alt="<?=e($post['title'])?>"></div>
<section class="section post-section"><div class="container post-layout"><article class="post-content reveal"><p class="post-lead"><?=e($post['intro'])?></p><?php foreach($post['sections'] as $section): ?><h2><?=e($section['heading'])?></h2><p><?=e($section['text'])?></p><?php endforeach; ?><div class="post-note"><span class="icon-box"><?=icon('file')?></span><div><h3>Plan the scope before the finish.</h3><p>Every project is shaped by existing conditions, selections, access, and local requirements. Final pricing is confirmed after an on-site assessment.</p></div></div><div class="post-footer-links"><a class="btn btn-secondary" href="<?=e(url('articles.php'))?>">All articles</a><a class="btn btn-primary" href="<?=e(url('contact.php?intent=consult'))?>">Discuss Your Project</a></div></article><aside class="post-sidebar"><div class="sidebar-card"><span class="eyebrow dark">RECENT ARTICLES</span><?php foreach($recent as $recentSlug=>$item): ?><a class="recent-post" href="<?=e(url('post.php?slug='.$recentSlug))?>"><img src="<?=e($item['image'])?>" alt=""><span><small><?=e($item['category'])?></small><b><?=e($item['title'])?></b></span></a><?php endforeach; ?></div><div class="sidebar-appointment"><span class="icon-box large"><?=icon('calendar')?></span><h3>Schedule a project conversation.</h3><p>Tell us what you are considering and where you are in the planning process.</p><a class="btn btn-primary btn-block" href="<?=e(url('contact.php?intent=consult'))?>">Book an Appointment</a><a class="sidebar-phone" href="tel:<?=e(BUSINESS_PHONE_RAW)?>"><?=icon('phone')?> <?=e(BUSINESS_PHONE)?></a></div></aside></div></section>
<?php require __DIR__.'/includes/footer.php'; ?>
