<?php
require_once __DIR__ . '/includes/functions.php';
if (empty($serviceKey)) {
    $serviceKey = 'kitchen';
}
$s = service_data($serviceKey);
$pageTitle = $s['name'];
$pageDescription = $s['intro'];
$primaryIntent = 'estimate';
$primaryLabel = 'Request an Estimate';
require 'includes/header.php';
?>
<section class="service-hero"><div class="service-hero-bg"><img src="<?=e($s['hero'])?>" alt="<?=e($s['name'])?>"></div><div class="container service-hero-grid"><div class="service-hero-copy"><span class="eyebrow"><?=e($s['eyebrow'])?></span><h1><?=e($s['title'])?></h1><p><?=e($s['intro'])?></p><div class="hero-actions"><a class="btn btn-primary" href="#estimate-form">Request an Estimate</a><a class="btn btn-secondary light" href="<?=e(url('contact.php?intent=consult'))?>">Book a Consult</a></div><div class="trust-row"><span><?=icon('file')?> Written scope</span><span><?=icon('camera')?> Milestone records</span><span><?=icon('shield')?> Change control</span></div></div><div class="hero-form" id="estimate-form"><?php $mode='estimate'; $selected=$s['short']; include 'includes/lead-form.php'; ?></div></div></section>
<section class="proof-strip"><div class="container proof-grid"><article><span class="icon-box"><?=icon('ruler')?></span><div><small>PLAN</small><h3>Scope clarity</h3><p>What is included, excluded, and assumed.</p></div></article><article><span class="icon-box"><?=icon('camera')?></span><div><small>VERIFY</small><h3>Quality gates</h3><p>Defined checks at critical construction stages.</p></div></article><article><span class="icon-box"><?=icon('file')?></span><div><small>CLOSE</small><h3>Project records</h3><p>Photos, summary, sign-off, and care notes.</p></div></article></div></section>
<section class="section"><div class="container split-grid"><div class="section-copy"><span class="eyebrow dark">PROJECT STRATEGY</span><h2><?=e($s['angle'])?></h2><p><?=e($s['range'])?></p><p class="disclaimer">Final pricing is confirmed after an on-site assessment.</p></div><div class="included-panel"><h3>What may be included</h3><div class="included-grid"><?php foreach($s['included'] as $item):?><span><?=icon('check')?> <?=e($item)?></span><?php endforeach;?></div></div></div></section>
<section class="section bg-mist"><div class="container"><div class="centered section-heading"><span class="eyebrow dark">THE PROJECT LIFECYCLE</span><h2>Every stage resolves a specific risk before the next begins.</h2></div><div class="timeline"><?php $stages=['Lead intake','Discovery consult','Site review','Scope development','Selections and approvals','Pre-start verification','Build and coordination','Milestone quality checks','Punch-list','Closeout package']; foreach($stages as $i=>$stage):?><article><b><?=str_pad((string)($i+1),2,'0',STR_PAD_LEFT)?></b><span><?=e($stage)?></span></article><?php endforeach;?></div></div></section>
<section class="section"><div class="container"><div class="section-head-row"><div><span class="eyebrow dark">QUALITY CONTROL</span><h2>C2C Signature Finish Protocol</h2></div><p>Quality is reviewed while correction is still practical, not only at the end.</p></div><div class="grid-3 qc-grid"><?php foreach([['Pre-start verification',['Selections ready','Protection plan confirmed','Scope questions resolved']],['Behind-the-walls check',['Rough work reviewed','Photos captured','Concealment authorized']],['Mid-project milestone',['Alignment and substrate','Material execution','Open items recorded']],['Finish quality check',['Fit and finish','Function testing','Detail corrections']],['Punch-list verification',['Owner walkthrough','Items assigned','Completion confirmed']],['Final closeout',['Documentation assembled','Care notes organized','Project handoff completed']]] as $gate):?><article><span><?=icon('shield')?></span><h3><?=e($gate[0])?></h3><ul><?php foreach($gate[1] as $item):?><li><?=e($item)?></li><?php endforeach;?></ul></article><?php endforeach;?></div></div></section>
<section class="section bg-navy"><div class="container split-grid light-copy"><div><span class="eyebrow">SCOPE + CHANGE ORDERS</span><h2>No surprises: changes are approved in writing before work continues.</h2><p>Every project distinguishes base scope, exclusions, allowances, assumptions, and requested changes.</p></div><div class="scope-tabs"><article><b>Included</b><span>Defined work and deliverables</span></article><article><b>Excluded</b><span>Known boundaries and owner responsibilities</span></article><article><b>Allowances</b><span>Selection budgets awaiting final choice</span></article><article><b>Change orders</b><span>Description, price, impact, approval</span></article></div></div></section>
<section class="section"><div class="container split-grid reverse"><div class="section-media"><img src="<?=e($s['hero'])?>" alt="<?=e($s['name'])?> detail"></div><div class="section-copy"><span class="eyebrow dark">OPTIONAL ENHANCEMENTS</span><h2>Structured options that can be evaluated before construction.</h2><div class="enhancement-list"><?php foreach($s['enhancements'] as $item):?><article><span><?=icon('sparkles')?></span><div><h3><?=e($item)?></h3><p>Reviewed for scope, compatibility, timing, and budget before approval.</p></div></article><?php endforeach;?></div></div></div></section>
<section class="section bg-mist"><div class="container closeout-grid"><div><span class="eyebrow dark">CLOSEOUT PACKAGE</span><h2>A clean finish includes a clean handoff.</h2><p>Your closeout package may include the final walkthrough, punch-list sign-off, photo record, completion summary, care notes, and invoice documents.</p></div><div class="document-stack small"><div class="doc-card back"></div><div class="doc-card middle"></div><div class="doc-card front"><span><?=icon('file')?></span><h3><?=e($s['short'])?> Project Closeout</h3><ul><li>Final walkthrough</li><li>Milestone photo set</li><li>Completion summary</li><li>Care notes and records</li></ul></div></div></div></section>
<section class="section"><div class="container split-grid"><div><span class="eyebrow dark">QUESTIONS</span><h2>Planning a <?=e(strtolower($s['short']))?> project in Western New York?</h2><p>These answers provide general planning context. Property-specific requirements are confirmed during review.</p></div><div class="accordion"><?php foreach($s['faqs'] as $i=>$faq):?><details <?=$i===0?'open':''?>><summary><?=e($faq[0])?></summary><p><?=e($faq[1])?></p></details><?php endforeach;?></div></div></section>
<?php require 'includes/footer.php'; ?>
